### ISSUE TITLE
Capturing HTTP error (status code & message)

### ISSUE THREAD

**Issue by kerphi** [jaubourg/jquery-jsonp#47]
Hello,

First of all, thank you for a such module. It is a good alternative to the native jquery jsonp dataType cause it allows to catch HTTP errors.
But, this lib seams not to be able to catch more than juste "there is an error"
It would be great to have the HTTP status code and the HTTP status message as parameters of the "error" callback.
Do you think it's doable ?

For example: if my jsonp server returns 
```
HTTP/1.1 500 Internal Server Error
```

I'd like to have:
```javascript
        error: function (opt, httpStatusCode, httpStatusMessage) {
          console.log(httpStatusCode); // 500
          console.log(httpStatusMessage); // Internal Server Error
        }
```
regards,
Stéphane

**Comment by ChrisRM** [comment]
:+1:

**Comment by jaubourg** [comment]
Your only option for this is to use CORS.

The plugin uses script tags and is thus unable to set HTTP request information nor recover HTTP response information.
